### PR TITLE
Fix/alamofire compatibility

### LINKED ISSUE #86: Alamofire and AFNetworking support
They are not intercepted by NSURLProtocol. Search issues in those project that are describing what to do to support the interception

### PR DESCRIPTION
**Pull request by MP0w**
Closes #86 

There was nothing to do except return valid header fields by default (application/json)
AFNetowrking/Alamofire/etc will just work but the user will have to set a proper NSURLSessionConfiguration. So I made `KakapoServer` public.

### CODE REVIEW

File: Source/KakapoServer.swift [hunk 1]
```diff
@@ -9,9 +9,34 @@
...
+ 
+ ```
+ let manager = AFURLSessionManager(sessionConfiguration: configuration)
+ ```
+ 
+ #### Alamofire
+ 
+ ```
+ let manager = Manager(configuration: configuration)
+ ```
```
Comment (joanromano) [inline Source/KakapoServer.swift:37]: You still need to register the Router here right? Also I don't think this should be part of this documentation but probably of the README.

**Comment by joanromano** [comment]
👍
